```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Homework 4

Research Questions: 

```{r, eval = TRUE}
# library statements 
# read in data
library(dplyr)
library(readr)
library(broom)
library(ggplot2)
library(tidymodels) 
library(tidyverse)
tidymodels_prefer() # Resolves conflicts, prefers tidymodel functions

set.seed(123)

basic_stats <- read_csv("Basic_Stats.csv")
qb_stats <- read_csv("Career_Stats_Passing.csv")
punt_return <- read_csv("Career_Stats_Punt_Return.csv")
punting <- read_csv("Career_Stats_Punting.csv")
receiving <- read_csv("Career_Stats_Receiving.csv")
kickers <- read_csv("Game_Logs_Kickers.csv")
oline_logs <- read_csv("Game_Logs_Offensive_Line.csv")
punters_logs <- read_csv("Game_Logs_Punters.csv")
qb_logs <- read_csv("Game_Logs_Quarterback.csv",na=c("","--","NA"))
rb_logs <- read_csv("Game_Logs_Runningback.csv")
wrandte_logs <- read_csv("Game_Logs_Wide_Receiver_and_Tight_End.csv")
```

```{r}
# data cleaning
qb_stats <- qb_stats %>%
    select(-Position)
    
qb_stats <- qb_stats %>%
    rename("Rating" = "Passer Rating")

basic_stats <- basic_stats %>%
    rename("Team" = "Current Team")

basic_stats <- basic_stats %>%
    rename("hsloc" = "High School Location")

basic_stats <- basic_stats %>%
    rename("Weight" = "Weight (lbs)")

basic_stats <- basic_stats %>%
    rename("Height" = "Height (inches)")

basic_stats <- basic_stats %>%
    filter(Position == "QB")

qb_comb <- merge(qb_stats, basic_stats, by="Name")


qb_comb$`Passes Attempted`[which(qb_comb$`Passes Attempted` == '--')] = 0
qb_comb <- qb_comb %>%
  mutate(`Passes Attempted` = as.numeric(`Passes Attempted`)) %>% 
    mutate(`Games Played` = as.numeric(`Games Played`))

qb_comb <- qb_comb %>% select(-c(Number, `Years Played`))


qb_comb <- qb_comb %>% mutate(Experience = as.numeric(stringr::str_extract(Experience,'[0-9]+')))



#qb_comb$hsloc
#####################

qb_logs <- qb_logs %>% 
  filter(Season != "Preseason", Outcome != "T", `Games Started` == 1) %>% 
  select(-c(Position, Week, `Game Date`, Score, `Games Played`, `Games Started`, Name, `Player Id`, Year, Season, Opponent, `Home or Away`))

qb_logs$Outcome <- as.factor(qb_logs$Outcome) 

qb_logs <- qb_logs %>% 
  mutate(Outcome = relevel(Outcome, ref='L')) #set reference level to be L

qb_logs[is.na(qb_logs)] = 0  #replaces NA values with 0
```



## Logistic Regression Model

```{r}
logistic_mod <- logistic_reg() %>%
    set_engine("glm") %>%
    set_mode('classification')

outcome_rec <- recipe(Outcome ~ ., data = qb_logs) %>%
  step_normalize(all_numeric_predictors())

logistic_mod_fit <- workflow() %>%
  add_model(logistic_mod) %>%
  add_recipe(outcome_rec) %>%
  fit(data = qb_logs)
```

```{r}
logistic_mod_fit %>%
  tidy() # Model Coefficients from Trained Model

library(dotwhisker)
tidy(logistic_mod_fit) %>%  # Viz of Trained Model Odds Ratios
  mutate(conf.low = exp(estimate - 1.96*std.error),conf.high = exp(estimate + 1.96*std.error)) %>% # do this first
  mutate(estimate = exp(estimate)) %>% # this second
  dwplot(dot_args = list(size = 2, color = "black"),
         whisker_args = list(color = "black"),
         vline = geom_vline(xintercept = 1, color = "grey50", linetype = 2)) + 
  labs(x = 'Odds Ratio') + 
  theme_classic()
```

```{r}
# Soft Predictions: Predicted Probabilities
logistic_output <-  qb_logs %>%
  bind_cols(predict(logistic_mod_fit, new_data = qb_logs, type = 'prob')) 

logistic_output %>% head()
```

```{r}
# Visualize predicted probabilities as a function of true outcome
logistic_output %>%
  ggplot(aes(x = Outcome, y = .pred_W)) +
  geom_boxplot() + 
  labs(y = 'Predicted Probability of Winning', x = 'Observed Outcome (L or W)') +
  theme_classic()
```

```{r}
logistic_output %>%
  ggplot(aes(x = Outcome, y = .pred_L)) +
  geom_boxplot() + 
  geom_hline(yintercept = 0.5, color='red') + 
  labs(y = 'Predicted Probability of LOSING', x = 'Observed Outcome (L or W)') +
  theme_classic()

logistic_output <- logistic_output %>%
  mutate(.pred_class = make_two_class_pred(.pred_L, levels(Outcome), threshold = .5)) #77.1 accuracy

head(logistic_output)

logistic_output %>%
  count(Outcome, .pred_class)

logistic_output %>%
  conf_mat(truth = Outcome, estimate = .pred_class)
```



## Random Forest Model

```{r}
outcome_rf_rec <- recipe(Outcome ~ ., data = qb_logs) %>%
  step_normalize(all_numeric_predictors())

rf_spec <- rand_forest() %>%
  set_engine(engine = 'ranger') %>% 
  set_args(mtry = NULL, # size of random subset of variables; default is floor(sqrt(ncol(x)))
           trees = 100, # Number of bags
           min_n = 5,
           probability = FALSE, # want hard predictions first
           importance = 'impurity') %>% 
  set_mode('classification') # change this for regression tree

rf_spec


outcome_rf_wf <- workflow() %>%
  add_model(rf_spec) %>%
  add_recipe(outcome_rf_rec)
```

```{r}
set.seed(123)
outcome_rf_fit <- outcome_rf_wf %>%
  fit(data = qb_logs)

outcome_rf_fit # check out OOB prediction error (accuracy = 1 - OOB prediction error)
```

```{r}
outcome_rf_OOB_output <- tibble(
  .pred_class = outcome_rf_fit %>% extract_fit_engine() %>% pluck('predictions'),
  Outcome = qb_logs %>% pull(Outcome))

bag_metrics <- metric_set(sens, yardstick::spec, accuracy)

outcome_rf_OOB_output %>% 
  bag_metrics(truth = Outcome, estimate = .pred_class)
```

```{r}
set.seed(123) #to get the same bootstrap samples, use same seed
outcome_rf_fit2 <- outcome_rf_wf %>%
  update_model(rf_spec %>% set_args(probability = TRUE)) %>%
  fit(data = qb_logs)

outcome_rf_fit2
```

```{r}
outcome_rf_OOB_output2 <- bind_cols(
  outcome_rf_fit2 %>% extract_fit_engine() %>% pluck('predictions') %>% as_tibble(),
  qb_logs %>% select(Outcome))

outcome_rf_OOB_output2 %>% 
  roc_curve(Outcome, W, event_level = "second") %>% autoplot()

outcome_rf_OOB_output2 %>% 
  roc_auc(Outcome, W, event_level = "second") #Area under Curve
```

```{r}
library(vip) #install.packages('vip')

outcome_rf_fit %>% extract_fit_engine() %>% vip() #based on impurity

outcome_rf_wf %>% #based on permutation
  update_model(rf_spec %>% set_args(importance = "permutation")) %>%
  fit(data = qb_logs) %>% extract_fit_engine() %>% vip()
```